spring:
  datasource:
    url: jdbc:mysql://192.168.153.131:3306/spring-boot-security
    username: root
    password: abc123##
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true